services:
  redis:
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:latest
      container_name: redis
      ports:
        - 16379:6379
      volumes:
        - ./components/redis/data:/data
      environment:
        TZ: Asia/Shanghai
      restart: always
      networks:
        - ai-knowledge-go
      command: redis-server --requirepass 1234 --appendonly yes
  mysql:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - ./components/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - ai-knowledge-go
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 16333:6333
      - 16334:6334
    volumes:
      - ./components/qdrant/data:/qdrant/storage
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      - ai-knowledge-go

networks:
  ai-knowledge-go:
    driver: bridge


  
